#!/bin/bash

echo "🔍 Getting Firebase iOS Credentials..."
echo ""
echo "Based on your firebase_options.dart, you have an iOS app configured:"
echo ""
echo "App ID: 1:1046904512204:ios:3eeca3ee2466a65e12ac69"
echo "Bundle ID: com.shamrai.sambad"
echo "Project: private-sambad"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📥 TO GET YOUR REAL CREDENTIALS:"
echo ""
echo "1. Open this URL:"
echo "   https://console.firebase.google.com/project/private-sambad/settings/general"
echo ""
echo "2. Scroll down to 'Your apps' section"
echo ""
echo "3. Look for iOS app with:"
echo "   • Bundle ID: com.shamrai.sambad"
echo "   • App ID: 1:1046904512204:ios:3eeca3ee2466a65e12ac69"
echo ""
echo "4. Click the iOS app icon"
echo ""
echo "5. Click 'GoogleService-Info.plist' button to download"
echo ""
echo "6. Save the file to your Downloads folder"
echo ""
echo "7. Run these commands:"
echo ""
echo "   cd ~/Downloads/app_user/frontend"
echo "   cp ~/Downloads/GoogleService-Info.plist ios/Runner/"
echo "   ./update_url_scheme.sh"
echo "   ./verify_firebase_config.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔐 WHAT YOU'LL GET:"
echo ""
echo "The real GoogleService-Info.plist contains:"
echo "• CLIENT_ID (for OAuth)"
echo "• REVERSED_CLIENT_ID (for URL schemes)"
echo "• All other Firebase configuration"
echo ""
echo "These are required for Phone Authentication to work on iOS."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  IF YOU DON'T SEE THE iOS APP:"
echo ""
echo "The app might have been deleted or you might not have access."
echo "In that case:"
echo ""
echo "1. Click 'Add app' → iOS icon"
echo "2. Enter Bundle ID: com.shamrai.sambad"
echo "3. App nickname: Sambad iOS"
echo "4. Download GoogleService-Info.plist"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ AFTER DOWNLOADING:"
echo ""
echo "Run this to complete the setup:"
echo ""
echo "cd ~/Downloads/app_user/frontend"
echo "cp ~/Downloads/GoogleService-Info.plist ios/Runner/"
echo "./update_url_scheme.sh"
echo "flutter clean && flutter pub get && cd ios && pod install && cd .."
echo "flutter run"
echo ""
