name: Deploy Admin Web

on:
  push:
    branches: [ main, master ]
    paths:
      - 'sambad_admin/frontend/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'any'
          channel: 'stable'

      - name: Get dependencies
        working-directory: ./sambad_admin/frontend
        run: flutter pub get

      - name: Build Flutter Web
        working-directory: ./sambad_admin/frontend
        run: flutter build web --release --base-href /sambad/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sambad_admin/frontend/build/web
